language: java
jdk:
   - openjdk7
   - oraclejdk7
script:
   -./gradlew check
   -./gradlew selenium Xvfb
deploy:
   provider: heroku
   api_key: c327f78e-0c7c-4b13-8821-4fff4788ea35
   app: hogridertictactoe

